export const ProductDataset = [
  {
    title: "sambar",
    id: 1,
    brand: "shirt",
    rate: "350",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 2,
    brand: "shirt",
    rate: "450",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 3,
    brand: "shirt",
    rate: "350",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 4,
    brand: "shirt",
    rate: "5550",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 5,
    brand: "shirt",
    rate: "35400",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 6,
    brand: "shirt",
    rate: "800",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 7,
    brand: "shirt",
    rate: "67700",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 8,
    brand: "shirt",
    rate: "3000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 9,
    brand: "shirt",
    rate: "2000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 10,
    brand: "shirt",
    rate: "5000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 11,
    brand: "shirt",
    rate: "34000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 12,
    brand: "shirt",
    rate: "34000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 13,
    brand: "shirt",
    rate: "5000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 14,
    brand: "shirt",
    rate: "36500",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 15,
    brand: "shirt",
    rate: "34000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 16,
    brand: "shirt",
    rate: "3600",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 17,
    brand: "shirt",
    rate: "36000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvgdfi",
  },
  {
    title: "sambar",
    id: 18,
    brand: "shirtdddd",
    rate: "37000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "iuduvguiiuaugdvidc;idgciywdcgi;u wdgfi",
  },
  {
    title: "sambar",
    id: 19,
    brand: "shirt",
    rate: "44000",
    img: "https://ik.imagekit.io/suriya/default-image.jpg?updatedAt=1700497073630",
    descroption: "i2222222222222",
  },
];